### ISSUE TITLE
Remove unnecessary packages

### ISSUE THREAD

**Issue by simoneb** [nearform/titus#656]
It seems that some packages are no longer used in  titus-frontend:

```
pretty-quick  
puppeteer
react-is
react-test-renderer
typescript
serve-handler
eslint-plugin-import
eslint-plugin-promise
```

make sure they are indeed not necessary (some may be used even if not referenced directly, as it may be peer dependencies of other packages), and remove those which are not used

**Comment by skywickenden** [comment]
Typescript is needed by eslint due to overriding `eslint-config-react-app` which is probably coming from `react-scripts`. The two eslint plugins may also be related to this. Can we please add something to [the docs](https://nf-titus.netlify.app/#/developers/packages/titus-frontend/?id=test-and-lint-the-frontend) about this.
