### ISSUE TITLE
Deploy on GCP issues

### ISSUE THREAD

**Issue by ovhemert** [nearform/titus#787]
Followed [the steps](https://nf-titus.netlify.app/#/devops/gcp/?id=deploy-titus-on-gcp) in the documentation to deploy Titus to GCP, but some parts are still missing to get it right the first time.

- There needs to be a bucket available for TF to store state, but there is no mention of it in the docs that this needs to be created manually before running `terraform apply`. When just running this command, there is a misleading error about invalid permissions. Also, a unique bucket name needs to be provided in `main.tf` first.
- On first terraform deployment, there is an error about the enabling of the "Cloud Resource Manager API". This can be avoided by adding `gcloud services enable cloudresourcemanager.googleapis.com` to the list of commands to run to enable needed API's.
- Docs should mention the **_only_** the first part of `config.auto.tfvars` should be changed, and not the other vars. I've also changed `artifact_registry_repository_name` for example, but that is causing errors in the GH deployment pipelines. The vars. are not supported everywhere yet.
- After succesful deployment, the backend service does not start because the `AUTH0_DOMAIN` env var is missing. When setting this to `AUTH0_DOMAIN=dummy` resolves the issue, but something should be added to TF/docs for this.
- All the docs mention the project path `infra/terraform/gcp/`, but this should be `infra/gcp/terraform/`.

**Comment by simoneb** [comment]
@ovhemert @Peterabsolon a few notes that you're probably aware of already, adding for tracking:

- we need to fix the GCP deployment, in particular with regards to the DB. It should work out of the box. The main issue I found (after those that were already fixed by @ovhemert) were permissions on the account used by the backend and db-manager projects. I couldn't find a way to modify those user's permissions in the GCP console so I created a new account, added the `Cloud SQL Client` and  `Secret Manager Secret Accessor` permissions to it, used that account when creating a new revision of backend and db-manager, and everything started working. We must port this change to terraform
- we need to see if the change in the frontend docker setup done by @Peterabsolon to make the client communicate correctl with the server requires further setup/documentation
