### ISSUE TITLE
Create deployment mechanism for Kubernetes

### ISSUE THREAD

**Issue by Vunovati** [nearform/titus#994]
We could use a Helm chart for Titus, which would speed things up for us when having to deploy it to Kubernetes.

A very useful feature to have would be to have the chart invoke database schema migrations from the Titus-DB-manager (by using [postgrator](https://www.npmjs.com/package/postgrator)) on deployment.

To do that, we need to replicate a pattern where one can run a one-off process that is spun up whenever we do a new deployment. An example of that on other platforms would be Heroku's release phase: https://devcenter.heroku.com/articles/release-phase

The desired flow would be:
1. Deploy the project
2. Run the DB migrations (if any), while the containers with old code are still running
3. If the migration succeeds run the containers with new code; if not, leave the old containers as they were

### Solution proposal

The release phase process can be replicated in k8s by using an approach suggested in this blog post:
https://andrewlock.net/deploying-asp-net-core-applications-to-kubernetes-part-7-running-database-migrations/

The author suggests using a combination of Job and init containers. He also explains the other options that were considered.

A Job is used to run a one-off command in a container on the k8s cluster. In this case, it is going to run the Titus-DB-manager image with the `npm run db:migrate` command.
The init containers will be added to the pod … and they will block the start of production code containers until the Job is run to completion successfully.

The init containers can know which job to wait for by looking for a matching release id in the job name.

**Comment by david-freistrom** [comment]
Andrelock's Blog shows overengineered to handle a problem which actually not exist if you run kuberetes with default settings and a common DB migration framework which versioned your schema definitions.

Kubernetes deployment strategy by default is [rolling-update](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-update-deployment) which replaces pods one by one by creating first a new one and after readiness stop and remove the old one.

By using this strategy there is no pitfall of concurrently running migration updates. 

If we have a Deployment with more then one instance running all init containers which maybe runs the database migration are executed by only the first is really changing the database. All further Pods init containers find an up to date schema version in the database already and do not see anything to run. Also here is no issue existing of redundant scheme migration updates running while roll out a new deployment.

Problems to face are not laying in redundancy or concurrency. They laying in having a zero downtime. To not have backward compatible schema migrations break zero downtime because old container cannot handle the new database schema. this is much harder to handle by using blue-green deployments for example and parallel running two database schemata at a time.

We have to be sure:
1) A rolling update strategy or similar which replace pods one by one is defined
2) Max Unavailable is set to 0 to have a zero downtime
3) Schema Migrations are backward compatible
4) Config a readiness and liveness probe for the container well
5) Define a well considered restart policy and back-off delay for the deployment to handle container failures

See also [weavworks way](https://www.weave.works/blog/how-to-correctly-handle-db-schemas-during-kubernetes-rollouts)

**Comment by Vunovati** [comment]
The solution you are proposing is good because it is simple. Unfortunately, this simplicity stems from some assumptions which are not always necessarily true.

1. Migrations are indempotent. - not necessarily the case. It is a best practice to make them transactional but it is not enforced and can easily be omitted. The original approach is also more useful as it could be reused for other non-idempotent scripts. If we wanted to prevent init containers from restarting the pod we'd also prevent our production container from being restarted.

2. A node running the init container running the migration script will be always on. - oftentimes the nodes running the highly available pods are installed on [AWS spot instances](https://aws.amazon.com/ec2/spot/?cards.sort-by=item.additionalFields.startDateTime&cards.sort-order=asc). If a long-running migration is running on that spot instance there is a higher chance something could go wrong halfway through. On the other hand, a one-off Job can be made to run on a more stable/expensive AWS machine.

Because of this I still think the original solution proposal is more robust and useful as a template.

**Comment by simoneb** [comment]
Let's keep the current approach which uses a Job for now, we can reconsider next. It's good to have multiple options though. Thanks both for the ideas!
